CREATE TABLE `clgdatabase`.`professor` ( `professor_id` INT(20) NOT NULL AUTO_INCREMENT ,
                                         `professor_name` VARCHAR(50) NOT NULL , 
                                         PRIMARY KEY (`professor_id`)) ENGINE = InnoDB;

CREATE TABLE `clgdatabase`.`department` ( `department_id` INT(20) NOT NULL AUTO_INCREMENT , 
                                          `department_name` VARCHAR(50) NOT NULL ,
                                           PRIMARY KEY (`department_id`)) ENGINE = InnoDB;

CREATE TABLE `clgdatabase`.`course` ( `course_id` INT(20) NOT NULL AUTO_INCREMENT ,
                                      `course_name` VARCHAR(50) NOT NULL ,
                                      `course_description` VARCHAR(1000) NOT NULL ,
                                      `did` INT(20) NOT NULL ,
                                      `pid` INT(20) NOT NULL ,
                                       PRIMARY KEY (`course_id`)) ENGINE = InnoDB;
                                       
ALTER TABLE `course` ADD CONSTRAINT `pid` FOREIGN KEY (`pid`) REFERENCES `professor`(`professor_id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `course` ADD CONSTRAINT `did` FOREIGN KEY (`did`) REFERENCES `department`(`department_id`) ON DELETE RESTRICT ON UPDATE CASCADE;


INSERT INTO `professor` (`professor_id`, `professor_name`) VALUES (NULL, 'Dr.Taghreed Zeweil'), (NULL, 'Dr.Mohamed Abbas'), 
                                                                  (NULL, 'Dr.Nevine Kamal'), (NULL, 'Dr.Sayed Elashtoukhy'), 
                                                                  (NULL, 'Dr.Shaaban Noseir'), (NULL, 'Dr.Mustafa Shawky'), 
                                                                  (NULL, 'Dr.Ahmed Khalifa'), (NULL, 'Dr.Hazem Elbarky'), 
                                                                  (NULL, 'Dr.khaled Elhagla'), (NULL, 'Dr.Dina Saadallah'),
                                                                  (NULL, 'Dr.Hicham Elmongui'), (NULL, 'Dr.Layla Abou Hadid'), 
                                                                  (NULL, 'Dr.Amr Elmasry'), (NULL, 'Dr.Marwan Eltorki'), 
                                                                  (NULL, 'Dr.Mervat Mikhail'), (NULL, 'Dr.Magdy Abdelazeem')
                                                                  

INSERT INTO `department` (`department_id`, `department_name`) VALUES (NULL, 'Computer and Communication Engineering'), 
                                                                     (NULL, 'Petrochemicals and Gas Engineering'), 
                                                                     (NULL, 'Construction and Architectural Engineering')

INSERT INTO `course` (`course_id`, `course_name`, `course_description`, `did`, `pid`) VALUES (NULL, 'Corrosion Engineering', 'Corrosion; its economic effect, environmental and metallurgical aspects, mechanism of\r\ncorrosion, types of cells responsible for corrosion. Modern theories of Thermodynamics and\r\nkinetics. Forms of Corrosion and protection: coating (metallic coating, inorganic coating,\r\norganic and temporary coating), Inhibitors (cathodic inhibitors, anodic inhibitors and adsorption\r\ninhibitors), cathodic protection, anodic protection, selection of the suitable material of\r\nconstruction Relevant to Gas and Petrochemical processes.', '2', '1'), 
                                                                                             (NULL, 'Applied Thermodynamics', 'Basic Concepts of Power generation and refrigeration. Heat pump cycles, vapor compression\r\ncycle, Refrigeration with Emphasises on turbo expanders and JT valve.', '2', '2'), 
                                                                                             (NULL, 'Fundamentals of Heat Transfer', 'Modes of heat transfer, calculations of heat transfer rates with special emphasis on\r\nconvection calculations, heat transfer applications; types of heat exchangers.', '2', '3'), 
                                                                                             (NULL, 'Petroleum Refining Engineering', 'Fundamental of oil refining and processing; fractionation, refining processes, thermal cracking,\r\ncatalytic cracking and reforming, petroleum products and their quality standards.', '2', '4'), 
                                                                                             (NULL, 'Introduction to Natural Gas Engineering', 'Natural gas, composition, classification, treatment processes, gas – vapor equilibrium,\r\ndistillation, hydrates, its effect and control, vapor and gases removal, gaseous treatment,\r\ngaseous acids injection, sulphur recovery, nitrogen removal, liquid hydrocarbons recovery.', '2', '5') 
                                                                                                                                                                 
INSERT INTO `course` (`course_id`, `course_name`, `course_description`, `did`, `pid`) VALUES (NULL, 'Design of R.C. Structures II', 'Paneled beams, Design of slender columns (braced and untraced), Design of simple reinforced concrete\r\nframes, Design of slab-type and cantilever-type stairs, Design of reinforced concrete beams subjected to\r\ncombined shear and torsion. Design of frames, Brackets, Windbags. Structural Systems for tall buildings.\r\nDesign of multistory frames. Design of concrete water tanks.', '3', '6'), 
                                                                                             (NULL, 'Design of Steel Structures', 'Specifications, loads, methods of design, analysis and design of tension and compression members,\r\ndesign of beams and columns, bolt connections and rivets, welding and building connections,\r\ncomposite beams and columns, and design of steel buildings.', '3', '7'),
                                                                                             (NULL, 'Design of Reinforced Concrete Structures-I', 'Introduction to Reinforced Concrete – Materials used in reinforced concrete – Mechanical properties\r\nof hardened concrete and reinforcing steel – Methods of design – Load factors and material factors –\r\nBehavior of reinforced concrete sections subjected to flexure for: untracked stage, working stress\r\nstage, and ultimate limit state - Design of sections subjected to flexure using both Ultimate Strength\r\nLimit state method and Working Stress method – Design of sections for shear – Bond, development\r\nlength, and reinforcement splices – Design of sections subjected to axial loads – Design of sections\r\nunder combined flexure and axial compression. Serviceability Limit states (deflection and cracking\r\nlimit states) – Floor systems – Design of solid reinforced concrete one-way and two-way slabs –\r\nDesign of floor beams – One-way and two-way hollow block slabs.', '3', '8'), 
                                                                                             (NULL, 'Design Studio', 'Introducing problems that are to be solved on both levels: concepts and ideas as well as working details.\r\nStudy of the factors and issues that understanding of human needs and purposes into significant architectural\r\nforms. The course presents architectural design as a synthesis of environmental concerns, behavioral\r\nresponses, functional requirements and technical systems. Design process and its stages. Emphasis on the\r\ndevelopment of insight into the solution of building design problems: how they are studied (analysis), how\r\nthey are approached and carried through (process) and how they are conceptualized and developed\r\n(synthesis). Issues of form and space, circulation patterns, geometry, space requirements, and structure\r\nsystems, are explored through studio design exercises, projects and discussions.', '3', '9'),
                                                                                             (NULL, 'Urban Design and Landscape', 'Contemporary theories, approaches, and principles in the field of urban design, Aanalysis\r\nand evaluation of the design of urban areas, spaces and complexes with emphasis on physical and social\r\nconsiderations and effects of public policies through case studies, Various themes in urban design.', '3', '10')
                                                                                                                                                                
INSERT INTO `course` (`course_id`, `course_name`, `course_description`, `did`, `pid`) VALUES (NULL, 'Data Structures-I', 'Representation of Elementary Data types, Arrays, Strings, Linear Structures and List Structures. Queues\r\nand Stacks. Tree structures and Graphs and their representation. High-level language Data Handling\r\nFacilities. Algorithms for Searching and Sorting.', '1', '11'), 
                                                                                             (NULL, 'Database Systems', 'Database systems: History and motivation, components of database systems; DBMS functions ; database\r\narchitecture and data independence . Data modeling: conceptual models; object-oriented model; relational\r\ndata model. Relational databases: Mapping conceptual schema to a relational schema; entity and\r\nreferential integrity; relational algebra and relational calculus. Database query languages: SQL; query\r\noptimization; 4th-generation environments; embedding non-procedural queries in a procedural language.', '1', '11'), 
                                                                                             (NULL, 'Computer Organization', 'Register level description of computer execution and the functional organization of a computer; essential\r\nelements of computer architecture; major functional components of a modern computer system.\r\nCharacteristics of machine codes: instruction formats and addressing modes. The elements of machine and\r\nassembly code programming. Memory hierarchy and organization. Interfacing and communication\r\nbetween processor and peripheral devices. Experiments provide laboratory experience in hardware and\r\nsoftware to interface memory and peripheral components to a computer system.', '1', '12'), 
                                                                                             (NULL, 'Discrete Structures for Computing', 'Basic mathematical notions of sets, relations, and functions, and operations ,logic and its role, propositional\r\nlogic, truth tables, issues of equivalence, limitations; predicate logic, its power and its limitations, proof\r\ntechniques; commonly occurring mathematical concepts such as graphs, trees; representational issues,\r\nrecursion; counting; combinatories.', '1', '13'), 
                                                                                             (NULL, 'Data Structures-II', 'Trees, binary search trees, heaps, equivalence classes, balanced binary search trees, searching techniques,\r\ninternal sorting, file processing (buffer pools), external sorting, indexing (ISAM, B-tree),graph theory\r\n(minimum spanning trees, topological sort, shortest path), hashing (open hashing, closed hashing.', '1', '13'), 
                                                                                             (NULL, 'Analysis and Design of Algorithms', 'Introduction to Computational Complexity. Asymptotic analysis of Upper and Average Complexity\r\nbounds. Standard Complexity Classes Time Complexity of iterative and recursive algorithms.\r\nFundamental Algorithmic Strategies . Greedy Algorithms. Divide and Conquer algorithms. Branch and\r\nBound Backtracking . Dynamic Programming , introduction to computability.', '1', '13'), 
                                                                                             (NULL, 'Artificial Intelligence', 'Fundamental issues. Search and constraint satisfaction. Knowledge representation and reasoning. Advanced\r\nsearch algorithms. Advanced knowledge representation and reasoning: temporal and spatial reasoning;\r\nuncertainty; knowledge representation for diagnosis. Machine learning and neural networks. Applications.', '1', '14'), 
                                                                                             (NULL, 'Programming-II', 'Information Hiding and Abstract Data Types. Object–Oriented Design versus Structured Design. Classes\r\nand Objects. Inheritance. Polymorphism. Operator Overloading . Generic Functions and Classes.', '1', '15'), 
                                                                                             (NULL, 'Probability and Statistics', 'Probability theory: axioms and basic laws. Random variables: motivation, mathematical definition,\r\ndiscrete and continuous random variables, probability distribution function, cumulative distribution function,\r\nexpectation and variance, moment generating function. Special distributions: binomial, geometric, Poisson,\r\nuniform, exponential, gamma, and normal distributions. Introduction to statistics: sampling, numerical\r\nsummaries, parameters estimation, distribution fitting, sampling distributions, confidence intervals,\r\nhypothesis testing.', '1', '15'), 
                                                                                             (NULL, 'Digital Logic Circuits-I', 'Boolean algebra and logic functions, Minimization of Function – Tabular minimization - Multifunction\r\nminimization- Arithmetic circuits- MSI and LSI logic design (Binary parallel adder – Decimal adder –\r\nMagnitude comparator – Decoder – Multiplexer - ROM – PLA) – Special functions (Symmetric –\r\nComplete) – Decomposition – Control Unit.', '1', '16'), 
                                                                                             (NULL, 'Digital Logic Circuits-II', 'Synchronous sequential systems (analysis- synthesis- state equivalence- machine minimization) –\r\nIncompletely specified machines – Asynchronous sequential systems (Design procedures – reduction of\r\nstates – flow table- Race Free State assignment) Linear machines', '1', '16')